# Look Up

In [2]:
import hebi
from time import sleep

ModuleNotFoundError: No module named 'hebi'

In [2]:
# Create lookup
lookup = hebi.Lookup()

In [3]:
# Wait 2 seconds for the module list to populate, and print out its contents
sleep(2)

for entry in lookup.entrylist:
    print(entry)

Family: Wheel Name: Right Mac Address: D8:80:39:A2:3A:66


In [4]:
# Create a group
group = lookup.get_group_from_names(['Wheel'], ['Right'])

if group == None:
    print('Group not found: Did you forget to set the module family and names above?')
exit(1)

print('Found group on network: size {0}'.format(group.size))

Found group on network: size 1


In [5]:
from time import sleep
lookup = hebi.Lookup()
# Give the Lookup process 2 seconds to discover modules
sleep(2)
print('Modules found on network:')
for entry in lookup.entrylist:
  print('{0} | {1}'.format(entry.family, entry.name))

Modules found on network:
Wheel | Right


# Feedback_Foreground

In [1]:
import hebi
from time import sleep

In [3]:
# Get a group
lookup = hebi.Lookup()
sleep(2)

group = lookup.get_group_from_names(['Wheel'], ['Right', 'Left'])
#group = lookup.get_group_from_names(['Arm'], ['Base', 'Shoulder', 'Elbow', 'Wrist1', 'Wrist2', 'Wrist3'])

if group == None:
    print('Group not found: Did you forget to set the module family and names above?')
exit(1)

for entry in lookup.entrylist:
    print(entry)

Family: Wheel Name: Left Mac Address: 54:10:EC:31:35:41
Family: Wheel Name: Right Mac Address: D8:80:39:A2:3A:66


In [7]:
# This is by default "100" - setting this to 5 here allows the console output to be more reasonable.
group.feedback_frequency = 5

In [8]:
# Retrieve feedback with a blocking call to "get_next_feedback".
# This constrains the loop to run at the feedback frequency above; we run for about 10 seconds here.

group_fbk = hebi.GroupFeedback(group.size)

In [9]:
for i in range(0, 100):
    # Pass in `group_fbk` to reuse the GroupFeedback instance
    timeout_ms = 500
    group_fbk = group.get_next_feedback(timeout_ms,group_fbk)
    if group_fbk != None:
        #print('Received feedback. Positions:{1:2d} {0}'.format(group_fbk.position, i))
        #print('Positions:{0} Velocitys:{1} Effortrs:{2}'.format(group_fbk.position, group_fbk.velocity, group_fbk.effort))
        print('Effortrs:{0}'.format(group_fbk.effort))

Effortrs:[0.14677614 0.5920863 ]
Effortrs:[0.1392743  0.58867335]
Effortrs:[0.14747709 0.5881852 ]
Effortrs:[0.13500184 0.5878973 ]
Effortrs:[0.148153  0.5938679]
Effortrs:[0.1235947  0.59787333]
Effortrs:[0.14703482 0.59223235]
Effortrs:[0.14237851 0.5861032 ]
Effortrs:[0.13250679 0.592854  ]
Effortrs:[0.13594478 0.5965632 ]
Effortrs:[0.13383359 0.593434  ]
Effortrs:[0.13191432 0.5981654 ]
Effortrs:[0.13449281 0.5936676 ]
Effortrs:[0.13795584 0.5872214 ]
Effortrs:[0.13165563 0.5733985 ]
Effortrs:[0.13729662 0.58049977]
Effortrs:[0.13025373 0.5811715 ]
Effortrs:[0.14657587 0.5900794 ]
Effortrs:[0.1503393 0.5856776]
Effortrs:[0.13264865 0.57371974]
Effortrs:[0.14259547 0.5908388 ]
Effortrs:[0.13624519 0.57789624]
Effortrs:[0.14635056 0.59165657]
Effortrs:[0.14435619 0.5930209 ]
Effortrs:[0.14167756 0.5955243 ]
Effortrs:[0.13334125 0.58354557]
Effortrs:[0.15482873 0.5792022 ]
Effortrs:[0.14163584 0.5937761 ]
Effortrs:[0.1396665 0.5912769]
Effortrs:[0.14069289 0.5891615 ]
Effortrs:[0.1242

# Feedback_Background

In [11]:
import hebi
from time import sleep

# Get a group
lookup = hebi.Lookup()
sleep(2)

#group = lookup.get_group_from_names(['Wheel'], ['Right'])
group = lookup.get_group_from_names(['Arm'], ['Base', 'Shoulder', 'Elbow', 'Wrist1', 'Wrist2', 'Wrist3'])


if group == None:
    print('Group not found: Did you forget to set the module family and names above?')
    exit(1)

# This is by default "100" - setting this to 5 here allows the console output to be more reasonable.
group.feedback_frequency = 5.0

In [32]:
def feedback_handler(group_fbk):
    print('Received feedback. Positions: {0}'.format(group_fbk.position)) 

In [33]:
# Add a callback to react to feedback received on a background thread.
# This function needs to accept 1 argument, `group_fbk`
group.add_feedback_handler(feedback_handler)

# Wait for 3 seconds and stop
sleep(3)
group.clear_feedback_handlers()

Received feedback. Positions: [ 0.10250664  0.23100542  0.72045326  2.65891511 -0.77837545  0.0119915 ]
Received feedback. Positions: [ 0.10243988  0.23093323  0.7203598   2.65881974 -0.77839643  0.01195717]
Received feedback. Positions: [ 0.10243225  0.23100282  0.72035599  2.65894062 -0.77836115  0.01192331]


# Command

In [1]:
from hebi import *
from time import sleep

# Get a group
lookup = Lookup()
sleep(2)

group = lookup.get_group_from_names(['Wheel'], ['Right', 'Left'])
#group = lookup.get_group_from_names(['Arm'], ['Base', 'Shoulder', 'Elbow', 'Wrist1', 'Wrist2', 'Wrist3'])

print('Modules found on network:')
for entry in lookup.entrylist:
  print('{0} | {1}'.format(entry.family, entry.name))

if not group:
    print('Group not found: Did you forget to set the module family and names above?')
    exit(1)

Modules found on network:
Wheel | Left
Wheel | Right


In [2]:
# Sets the command lifetime to 100 milliseconds
group.command_lifetime = 100

In [3]:
# Nm/rad
spring_constant = -1.0
group_command = GroupCommand(group.size)

In [6]:
# Add a callback function to respond to feedback with a "virtual spring" command
def feedback_handler(group_fbk):
    # Apply Hooke's law: F = -k * x
    group_command.effort = [spring_constant * group_fbk.position[0], -spring_constant * group_fbk.position[1]] # 原点に戻るフィードバック
    #group_command.effort = spring_constant #無限回転
    group.send_command(group_command)

In [7]:
group.add_feedback_handler(feedback_handler)

# Control the robot at 100Hz for 20 seconds
group.feedback_frequency = 100.0
sleep(20)
group.clear_feedback_handlers()

# Kinematics

In [74]:
from hebi import *
from math import pi
from time import sleep

# Get a group
lookup = Lookup()

sleep(2)

#group = lookup.get_group_from_names(['Wheel'], ['Right'])
group = lookup.get_group_from_names(['Arm'], ['Base', 'Shoulder', 'Elbow', 'Wrist1', 'Wrist2', 'Wrist3'])

if not group:
    print('Group not found: Did you forget to set the module family and names above?')
    exit(1)

for entry in lookup.entrylist:
    print(entry)

Family: Arm Name: Base Mac Address: 54:10:EC:31:88:7C
Family: Arm Name: Elbow Mac Address: D8:80:39:EE:D0:2F
Family: Arm Name: Shoulder Mac Address: 54:10:EC:31:84:71
Family: Arm Name: Wrist2 Mac Address: 54:10:EC:31:66:2C
Family: Arm Name: Wrist1 Mac Address: D8:80:39:EE:C3:97
Family: Arm Name: Wrist3 Mac Address: 54:10:EC:31:0E:73


In [75]:
# Create a simple kinematic description of the arm 
kin = robot_model.RobotModel()
#kin.add_actuator('X8-9')
#kin.add_bracket('X5-LightBracket', mount='left')

kin.add_actuator('X8-9')
kin.add_bracket('X5-HeavyBracket', mount='right-outside')
kin.add_actuator('X8-9')
kin.add_link('X5', extension=0.325, twist=pi)
kin.add_actuator('X5-9')
kin.add_link('X5', extension=0.325, twist=pi)
kin.add_actuator('X5-1')
kin.add_bracket('X5-LightBracket', mount='right')
kin.add_actuator('X5-1')
kin.add_bracket('X5-LightBracket', mount='right')
kin.add_actuator('X5-1')

In [76]:
# Add a callback function to print (x,y,z) position
def feedback_handler(group_fbk):
    transform = kin.get_end_effector(group_fbk.position) # 4×4行列
    print('x = {0:.3f} y = {1:.3f} z = {2:.3f}'.format(transform.item(0, 3), transform.item(1, 3), transform.item(2, 3)))

In [85]:
group.add_feedback_handler(feedback_handler)

# Control the robot at 100Hz for 30 seconds
group.feedback_frequency = 1
sleep(10)

group.clear_feedback_handlers()

x = 0.264 y = 0.227 z = 0.006
x = 0.264 y = 0.227 z = 0.006
x = 0.264 y = 0.227 z = 0.006
x = 0.264 y = 0.227 z = 0.006
x = 0.264 y = 0.227 z = 0.006
x = 0.264 y = 0.227 z = 0.006
x = 0.264 y = 0.227 z = 0.006
x = 0.264 y = 0.227 z = 0.006
x = 0.264 y = 0.227 z = 0.006
x = 0.264 y = 0.227 z = 0.006


# IK(逆運動学)

In [87]:
from hebi import *
from math import pi
from time import sleep

# Get a group
lookup = Lookup()
sleep(2)

#group = lookup.get_group_from_names(['Wheel'], ['Right'])
group = lookup.get_group_from_names(['Arm'], ['Base', 'Shoulder', 'Elbow', 'Wrist1', 'Wrist2', 'Wrist3'])

if not group:
    print('Group not found: Did you forget to set the module family and names above?')
    exit(1)

In [88]:
# Create a simple kinematic description of the arm 
kin = robot_model.RobotModel()
#kin.add_actuator('X8-9')
#kin.add_bracket('X5-LightBracket', mount='left')

kin.add_actuator('X8-9')
kin.add_bracket('X5-HeavyBracket', mount='right-outside')
kin.add_actuator('X8-9')
kin.add_link('X5', extension=0.325, twist=pi)
kin.add_actuator('X5-9')
kin.add_link('X5', extension=0.325, twist=pi)
kin.add_actuator('X5-1')
kin.add_bracket('X5-LightBracket', mount='right')
kin.add_actuator('X5-1')
kin.add_bracket('X5-LightBracket', mount='right')
kin.add_actuator('X5-1')

In [122]:
target_xyz = [0.7, -0.1, 0.3]

if not group.send_feedback_request():
    print('Could not send feedback request.')
    exit(1)

group_fbk = group.get_next_feedback()

if not group_fbk:
    print('Could not get feedback.')
    exit(1)

initial_joint_angles = group_fbk.position

In [123]:
# ------------------------------------------------------------------------------
# Get IK solution with multiple objectives
# ------------------------------------------------------------------------------

# Just multiple objective
position_objective = robot_model.endeffector_position_objective(target_xyz)

min_positions = [-pi, 0.0, -2.7, -pi,-pi, -2*pi]
max_positions = [pi, 1.2, 2.7, pi, -pi/2, 2*pi]

joint_limit = robot_model.joint_limit_constraint(min_positions, max_positions)
ik_result_joint_angles = kin.solve_inverse_kinematics(initial_joint_angles, position_objective, joint_limit)

transform = kin.get_end_effector(ik_result_joint_angles)

print('Target Position:\n{0}'.format(target_xyz))
print('IK joint angles:\n{0}'.format(ik_result_joint_angles))
print('FK of IK joint angles:\n{0}'.format(transform[0:3,3].A1))

Target Position:
[0.7, -0.1, 0.3]
IK joint angles:
[ 0.18743549  0.32249357 -0.28459296  5.82840796 -3.04926855  0.01331494]
FK of IK joint angles:
[ 0.61205459 -0.08375131  0.27474266]


In [124]:
# ------------------------------------------------------------------------------
# Send commands to the physical robot
# ------------------------------------------------------------------------------

group.command_lifetime = 100

# Move the arm (note - could use the HEBI Trajectory API to do this smoothly)
group_cmd = GroupCommand(group.size)
group_cmd.position = ik_result_joint_angles

# Note - the arm will go limp after the 100 ms command lifetime,
# so we repeat the command in a loop here until we terminate after approximately 5 seconds
for i in range(0, 200):
    group.send_command(group_cmd)
    sleep(0.05)

# Trajectory

In [381]:
from hebi import *
from math import pi
from time import sleep
import numpy as np

# Get a group
lookup = Lookup()
sleep(2)

#group = lookup.get_group_from_names(['Wheel'], ['Right'])
group = lookup.get_group_from_names(['Arm'], ['Base', 'Shoulder', 'Elbow', 'Wrist1', 'Wrist2', 'Wrist3'])

if not group:
    print('Group not found: Did you forget to set the module family and names above?')
    exit(1)

In [382]:
num_joints = group.size
group.command_lifetime = 100

if not group.send_feedback_request():
    print('Could not send feedback request.')
    exit(1)

group_fbk = group.get_next_feedback()

if not group_fbk:
    print('Could not get feedback.')
    exit(1)

In [383]:
# ------------------------------------------------------------------------------
# Position, velocity, and acceleration waypoints.
# Each column is a separate waypoint - each row is a different joint
# ------------------------------------------------------------------------------

In [384]:
# [Baseの回転軸, 0, pi/2, 0 , 0 ],
# [Shoulderの回転軸, 0, 0 , -pi/2, 0],.............

positions = np.zeros((num_joints, 5))
positions[0:6, 0] = group_fbk.position[0:6].T
positions[0:6, 1] = group_fbk.position[0:6].T
positions[0:6, 2] = group_fbk.position[0:6].T
positions[0:6, 3] = group_fbk.position[0:6].T
positions[0:6, 4] = group_fbk.position[0:6].T
positions[0, 1:5] = 0
positions[1, 2] = 0.5
positions[1, 3] = pi/4
positions[1, 4:5] = 1.0
positions[2, 1] = pi/2
positions[2, 2:5] = 1.0
positions[3, 1:5] = pi

np.set_printoptions(precision=3, suppress=True)
positions

array([[-0.002,  0.   ,  0.   ,  0.   ,  0.   ],
       [ 0.963,  0.963,  0.5  ,  0.785,  1.   ],
       [ 2.097,  1.571,  1.   ,  1.   ,  1.   ],
       [ 2.554,  3.142,  3.142,  3.142,  3.142],
       [-1.635, -1.635, -1.635, -1.635, -1.635],
       [ 0.013,  0.013,  0.013,  0.013,  0.013]])

In [385]:
# 0, nan, nan, nan, 0
# 0, nan, nan, nan, 0
velocities = np.zeros((num_joints, 5))
velocities[0:6, 1:4] = np.nan

# 0, nan, nan, nan, 0
# 0, nan, nan, nan, 0
accelerations = velocities

# 5秒ごとに
time = np.linspace(0, 2, 5)

In [386]:
velocities

array([[ 0., nan, nan, nan,  0.],
       [ 0., nan, nan, nan,  0.],
       [ 0., nan, nan, nan,  0.],
       [ 0., nan, nan, nan,  0.],
       [ 0., nan, nan, nan,  0.],
       [ 0., nan, nan, nan,  0.]])

In [387]:
accelerations

array([[ 0., nan, nan, nan,  0.],
       [ 0., nan, nan, nan,  0.],
       [ 0., nan, nan, nan,  0.],
       [ 0., nan, nan, nan,  0.],
       [ 0., nan, nan, nan,  0.],
       [ 0., nan, nan, nan,  0.]])

In [388]:
time

array([0. , 0.5, 1. , 1.5, 2. ])

In [389]:
trajectory = trajectory.create_trajectory(time, positions, velocities, accelerations)

In [390]:
# Follow the trajectory
group_cmd = GroupCommand(num_joints)
period = 0.01
duration = trajectory.duration

In [391]:
t = 0.0

while(t < duration):
    pos_cmd, vel_cmd, eff_cmd = trajectory.get_state(t)
    group_cmd.position = pos_cmd
    group_cmd.velocity = vel_cmd
    group.send_command(group_cmd)
    
    t = t + period
    sleep(period)