In [1]:
import hebi
from time import sleep
import numpy as np

lookup = hebi.Lookup()
sleep(2)

group = lookup.get_group_from_names(['Wheel'], ['IO_BOARD', 'Right', 'Left'])

if group is None:
    print('Group not found: Did you forget to set the module family and names above?')
    exit(1)

for entry in lookup.entrylist:
    print(entry)

Family: Wheel Name: IO_BOARD Mac Address: D8:80:39:A1:A9:53
Family: Wheel Name: Right Mac Address: D8:80:39:A2:3A:66
Family: Wheel Name: Left Mac Address: 54:10:EC:31:35:41


In [40]:
def print_bank(pin_bank, bank_label):
    if(bank_label == 'a'):
        pin = 1
        print('Pin {0} {1} float data: {2}'.format(bank_label, pin, pin_bank.get_float(pin)))
    elif(bank_label == 'b'):
        print('Pin {0} {1} int data: {2}, Pin {3} {4} int data: {5}'.format(bank_label, 1, pin_bank.get_int(1), bank_label, 2, pin_bank.get_int(2)))
    '''
    for i in range(0, 8):
        pin = i + 1
        if (pin_bank.has_float(pin)):
            print('Pin {0} {1} float data: {2}'.format(bank_label, pin, pin_bank.get_float(pin)))
        if (pin_bank.has_int(pin)):
            print('Pin {0} {1} int data: {2}'.format(bank_label, pin, pin_bank.get_int(pin)))
    '''

In [2]:
def feedback_handler(group_fbk):
    # Container to the IO feedback
    io = group_fbk.io
    #print_bank(io.a, 'a')
    #print_bank(io.b, 'b')
    #print_bank(io.c, 'c')
    #print_bank(io.d, 'd')
    #print_bank(io.e, 'e')
    #print_bank(io.f, 'f')
    
    B2 = np.asarray(io.b.get_int(2))
    print(B2)
    #if(B1[0] == 1):
    #    print(group_fbk.accelerometer.item(1,0))

In [3]:
group.add_feedback_handler(feedback_handler)
group.feedback_frequency = 10

# Wait 10 seconds
sleep(10)

group.feedback_frequency = 0.0
group.clear_feedback_handlers()

[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[0 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[0 0 0]
[0 0 0]


In [4]:
group_fbk = hebi.GroupFeedback(group.size)
print('{0}'.format(group_fbk.io))